#!/bin/bash
git checkout opencl
git submodule update --init --recursive
git submodule init
git submodule update
git submodule foreach git checkout master
git submodule set-branch --branch fcontrol opencl
